from fhir_converter.discharge_summary import create_fhir_bundle_discharge_summary
from fhir_converter.prescription import create_prescription
from fhir_converter.diagnostic_report import create_diagnostic_report
from fhir_converter.op_consult import create_opconsult_record